### ISSUE TITLE
Create a logo for URL Shortener

### ISSUE THREAD

**Issue by Rajdeepc** [Rajdeepc/url-shortener#9]
## Guidelines

Make a URL shortener logo with 128X128 dimension
Update README.md and align it to center

**Comment by Priyanshu-official** [comment]
Can I Do this

**Comment by Rajdeepc** [comment]
Go ahead. Anyonr can raise a PR

**Comment by Priyanshu-official** [comment]
@Rajdeepc  pls tell if any Specific need Should be In the logo or I make My self

**Comment by Rajdeepc** [comment]
The app is same like bitly. You can come up with 2-3 ideas. Would love to see few.

**Comment by Priyanshu-official** [comment]
Nice

**Comment by Priyanshu-official** [comment]
@Rajdeepc Sorry for Interrupt can you tell me  **razorurl** Will be Site Name

**Comment by Rajdeepc** [comment]
Yes @Priyanshu-official

**Comment by Priyanshu-official** [comment]
Ok Thank you

**Comment by Priyanshu-official** [comment]
@Rajdeepc  I have Created one How I can Show you

**Comment by Priyanshu-official** [comment]
@Rajdeepc  I am adding to Design let me know Which you Like or any Changes.
![Capture1](https://user-images.githubusercontent.com/55912091/95018218-e1903300-067b-11eb-8759-62d714d02b4e.PNG)
![Capture2](https://user-images.githubusercontent.com/55912091/95018221-e3f28d00-067b-11eb-91d5-d408fe4c6337.PNG)

**Comment by Rajdeepc** [comment]
The second one without the upper and lower border. Please do the changes and raise a PR to master

**Comment by Priyanshu-official** [comment]
Thank you Like it  @Rajdeepc

**Comment by Priyanshu-official** [comment]
@Rajdeepc  I have one Question Before pr Can you tell me Image should be after
**Scalable URL Shortener Web Application**
or Before

**Comment by Rajdeepc** [comment]
Same like this please. 
https://github.com/Rajdeepc/teleport

**Comment by Priyanshu-official** [comment]
@Rajdeepc Please Review my PR

**Comment by Priyanshu-official** [comment]
@Rajdeepc  you Not Part of hacktoberfest it Shows not Label
if you can Label pls label it

**Comment by Rajdeepc** [comment]
Its labelled. Check again
